version: "3.4"
services:
  netbox:
    ports:
      - 8010:8080
    healthcheck:
      retries: 15
      start_period: 300s
    environment:
      SKIP_SUPERUSER: "false"
    volumes:
      - netbox-config-files:/etc/netbox/config:z,ro
      - netbox-media-files:/opt/netbox/netbox/media:rw
      - netbox-reports-files:/opt/netbox/netbox/reports:rw
      - netbox-scripts-files:/opt/netbox/netbox/scripts:rw
