version: "3.4"
services:
  git-checkout:
    image: bitnami/git:latest
    working_dir: /temp
    environment:
      VOLUME_LOCATION: /netbox-config-files
    command: >
      bash -c "
        find /temp -mindepth 1 -delete && 
        find /netbox-config-files -mindepth 1 -delete &&
        git clone https://github.com/vincentrm89/netbox-docker.git &&
        cp -R ./netbox-docker/configuration/. /netbox-config-files
      "
    volumes:
      - netbox-config-files:/netbox-config-files

  netbox:
    ports:
      - 8010:8080
    healthcheck:
      retries: 15
      start_period: 300s
    environment:
      SKIP_SUPERUSER: "false"
    volumes:
      - netbox-config-files:/etc/netbox/config:z,ro
      - netbox-media-files:/opt/netbox/netbox/media:rw
      - netbox-reports-files:/opt/netbox/netbox/reports:rw
      - netbox-scripts-files:/opt/netbox/netbox/scripts:rw

volumes:
  netbox-config-files:
    driver: local
  netbox-media-files:
    driver: local
  netbox-postgres-data:
    driver: local
  netbox-redis-cache-data:
    driver: local
  netbox-redis-data:
    driver: local
  netbox-reports-files:
    driver: local
  netbox-scripts-files:
    driver: local